#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Linux installation steps
# -----------------------------------------------------------------------------
#
# Sourced (not executed) by ../../install.sh, so DOTFILES_DIR, DOTFILES_DISTRO,
# DRY_RUN and the info()/run() helpers are already defined here.
#
# Contract with the shared installer:
#   - install the packages this OS needs
#   - set NVM_SH to this OS's nvm.sh, which the shared NVM step then sources

# -----------------------------------------------------------------------------
# Validate environment
# -----------------------------------------------------------------------------

if [[ "$DOTFILES_DISTRO" != "arch" ]]; then
    echo "Unsupported Linux distribution: ${DOTFILES_DISTRO:-unknown}"
    echo "Only Arch-based distributions are supported so far."
    echo "Add os/linux support for your package manager to continue."
    exit 1
fi

if ! command -v pacman &>/dev/null; then
    echo "pacman was not found, but the distro reports as Arch-based."
    exit 1
fi

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

# Manifests are one package per line with # comments and blank lines allowed;
# this flattens them to a space-separated list.
read_manifest() {
    sed -e 's/#.*//' -e '/^[[:space:]]*$/d' "$1" | tr '\n' ' '
}

# -----------------------------------------------------------------------------
# Repository packages
# -----------------------------------------------------------------------------

PACMAN_MANIFEST="$DOTFILES_DIR/os/linux/pacman.txt"

if [[ -f "$PACMAN_MANIFEST" ]]; then
    packages="$(read_manifest "$PACMAN_MANIFEST")"

    if [[ -n "${packages// /}" ]]; then
        info "Installing pacman packages..."

        # --needed skips anything already present, so this is safe to re-run.
        # Left interactive on purpose: pacman shows what it's about to do.
        run "sudo pacman -S --needed $packages"
    fi
else
    echo "No pacman.txt found, skipping repository packages."
fi

# -----------------------------------------------------------------------------
# AUR packages
# -----------------------------------------------------------------------------

AUR_MANIFEST="$DOTFILES_DIR/os/linux/aur.txt"

if [[ -f "$AUR_MANIFEST" ]]; then
    aur_packages="$(read_manifest "$AUR_MANIFEST")"

    if [[ -n "${aur_packages// /}" ]]; then
        if command -v paru &>/dev/null; then
            aur_helper="paru"
        elif command -v yay &>/dev/null; then
            aur_helper="yay"
        else
            aur_helper=""
        fi

        if [[ -n "$aur_helper" ]]; then
            info "Installing AUR packages with $aur_helper..."

            run "$aur_helper -S --needed $aur_packages"
        else
            echo "No AUR helper (paru/yay) found, skipping: $aur_packages"
        fi
    fi
fi

# -----------------------------------------------------------------------------
# NVM location
# -----------------------------------------------------------------------------

# Arch's nvm package installs system-wide rather than cloning into ~/.nvm;
# matches os/linux/zsh/exports.zsh.
NVM_SH="/usr/share/nvm/nvm.sh"
#
# All of them describe *this* machine's hardware, so they would be wrong on any
# other one, and the nwg-displays pair is regenerated by that tool — tracking
# them means fighting it on every display rearrangement.
HYPR_USER_CONFIGS=(
    userprefs.conf
    keybindings.conf
    windowrules.conf
)

# Note on precedence: hyprland.conf sources userprefs.conf last, so anything set
# there outranks the active theme. Keep structure and behaviour here, and leave
# colors/gaps/rounding/blur to the theme, or theme switching will look broken.
install_hypr_configs() {
    local src="$HOME/.dotfiles/os/linux/hypr"
    local dest="$HOME/.config/hypr"
    local file

    [[ -d "$DOTFILES_DIR/os/linux/hypr" ]] || return 0

    info "Linking Hyprland user configuration..."

    # Created rather than required: on a fresh machine where Hyprland has never
    # run, ~/.config/hypr may not exist yet, and skipping here would be silent.
    # Without HyDE these files are linked but inert — Hyprland's own default
    # hyprland.conf doesn't source them.
    run "mkdir -p '$dest'"

    for file in "${HYPR_USER_CONFIGS[@]}"; do
        if [[ -e "$DOTFILES_DIR/os/linux/hypr/$file" ]]; then
            link_config "$src/$file" "$dest/$file"
        fi
    done
}

# -----------------------------------------------------------------------------
# Lua desktop session
# -----------------------------------------------------------------------------

# Installs a second login session that runs this repo's Lua Hyprland config,
# leaving the existing one alone. Both appear at the login screen, so switching
# between them is a choice made there, and removing the entry below reverts to
# whatever was there before with nothing else touched.
#
# The config is named with --config rather than by exporting HYPRLAND_CONFIG.
# HyDE assigns that variable unconditionally in its own uwsm env fragment, so
# using it would mean winning an ordering contest inside uwsm's env.d for a file
# this repo does not own. --config is read in preference to the variable
# (verified on 0.56.2) and needs no HyDE file edited.
#
# The entry is a template because the path must be absolute: Desktop Entry
# field codes have nothing for the home directory, and /usr/share/wayland-
# sessions is root-owned and shared between users.
SESSION_ENTRY="/usr/share/wayland-sessions/hyprland-dotfiles.desktop"

install_desktop_session() {
    local desktop_dir="$DOTFILES_DIR/os/linux/desktop"
    local template="$desktop_dir/session/hyprland-dotfiles.desktop.in"
    local init_lua="$HOME/.dotfiles/os/linux/desktop/init.lua"

    [[ -f "$template" ]] || return 0

    # A config that does not parse must never reach the login screen, where the
    # only way to read the error is from another machine. Hyprland parses it
    # without starting a session, so this costs nothing and catches everything
    # the compositor would have refused.
    info "Verifying the Lua Hyprland configuration..."

    if ! "$desktop_dir/verify-config.sh" "$desktop_dir/init.lua"; then
        echo "Refusing to install the session entry while the config has errors."
        return 1
    fi

    # Verifying the config proved the compositor would accept it and proved
    # nothing about the command line that launches it: a malformed Exec fails
    # inside uwsm's argument parsing, before Hyprland is reached, and a display
    # manager reports that as a failed login rather than a bad command. A dry
    # run writes and starts nothing, so it is safe to do from inside a running
    # session, and it is the only check that covers the Exec line itself.
    local exec_line dry_run_line

    # Read from the template and substituted exactly as the entry will be, so
    # this tests the line the display manager will actually run. Rebuilding an
    # equivalent command here would let the two drift, and a check that passes
    # while the installed entry is broken is worse than no check.
    exec_line="$(sed -n 's/^Exec=//p' "$template" | sed "s|@INIT_LUA@|$init_lua|")"

    if command -v uwsm &> /dev/null && [[ "$exec_line" == uwsm\ start\ * ]]; then
        info "Checking the session command line..."

        dry_run_line="${exec_line/uwsm start/uwsm start -n}"

        if ! eval "$dry_run_line" &> /dev/null; then
            echo "uwsm rejected the session command line:"
            eval "$dry_run_line" 2>&1 | sed 's/^/    /'
            echo ""
            echo "Refusing to install a session entry that cannot start."
            return 1
        fi

        echo "    uwsm accepts it"
    fi

    info "Installing the 'Hyprland (dotfiles)' session..."

    # Needs root: session entries are system-wide. Written via a temporary file
    # so a failed substitution cannot leave a half-written entry that SDDM would
    # still offer.
    local staged="${TMPDIR:-/tmp}/hyprland-dotfiles.desktop.$$"

    if [[ "$DRY_RUN" == true ]]; then
        echo "[dry-run] install $template -> $SESSION_ENTRY (INIT_LUA=$init_lua)"
        return 0
    fi

    sed "s|@INIT_LUA@|$init_lua|" "$template" > "$staged"

    sudo install -Dm644 "$staged" "$SESSION_ENTRY"
    rm -f "$staged"

    echo "    Log out and pick 'Hyprland (dotfiles)' to try it."
    echo "    The existing session is untouched and still the one to fall back to."
}

# The bar reads its colours from a generated JSON file rather than from
# anything tracked, so a fresh machine needs it written once before the first
# login. Without it the vendored pill falls back to its own warm palette --
# usable, but not this scheme.
#
# Cheap and idempotent, so it runs every install: it is also how a palette.lua
# edit reaches the bar.
# The pill shells out to helpers it expects at ~/.config/hypr/scripts. A whole
# directory rather than file-by-file, so a script added to the repo is live
# without touching the installer.
#
# ~/.config/hypr is otherwise HyDE's, but it ships no scripts/ of its own, so
# nothing is displaced. Worth remembering that HyDE deploys with `cp -rf`,
# which writes *through* a symlink -- if it ever grows a scripts/ directory,
# this link is how its contents would land in the repo.
install_pill_scripts() {
    local scripts="$DOTFILES_DIR/os/linux/desktop/quickshell/scripts"

    [[ -d "$scripts" ]] || return 0

    link_config "$scripts" "$HOME/.config/hypr/scripts"
}

# Generates every config that carries a colour, from lib/palette.lua. The
# session does this at login too; doing it here means a fresh machine has them
# before its first login rather than one login later.
install_theme() {
    local render="$DOTFILES_DIR/os/linux/desktop/render-theme.lua"

    [[ -x "$render" ]] || return 0

    info "Rendering theme files from the palette..."

    run "lua '$render' --verbose"
}

# The bar ignores generated colours entirely while paletteMode is "static",
# which is its default, so this has to run once before the colours mean
# anything. Idempotent, so it simply runs every install.
install_pill_flags() {
    local script="$DOTFILES_DIR/os/linux/desktop/quickshell/pill-flags.sh"

    [[ -x "$script" ]] || return 0

    info "Setting the bar to use generated colours..."

    run "$script"
}

# Called by the shared installer after the ~/.dotfiles symlink exists.
os_link_configs() {
    # Additive and HyDE-independent: these are user-tier files that HyDE seeds
    # but never rewrites, so they link whether or not HyDE is present.
    install_hypr_configs

    # Also additive: a second session entry alongside whatever is already
    # installed, never a replacement for it.
    install_desktop_session

    # All three write generated files outside the repo, so they are safe
    # alongside HyDE.
    install_theme

    install_pill_flags

    install_pill_scripts

    # Kitty and Fastfetch are linked whether or not HyDE is present.
    #
    # They used to be skipped here, to leave the existing desktop untouched.
    # That skip is what made them the last things still themed by HyDE, and
    # removing HyDE would have taken the terminal's colours and the shell
    # banner's logo with it. Owning them now is what makes that removal a
    # non-event.
    #
    # Safe to take over: link_config moves whatever is there to
    # <name>.pre-dotfiles first, so HyDE's own files are kept rather than
    # overwritten, and neither program is session-specific -- the same terminal
    # config serves both sessions while both exist.
    info "Configuring Kitty..."

    run "mkdir -p '$HOME/.config/kitty'"

    link_config \
        "$HOME/.dotfiles/kitty/kitty.conf" \
        "$HOME/.config/kitty/kitty.conf"

    link_config \
        "$HOME/.dotfiles/kitty/theme.conf" \
        "$HOME/.config/kitty/theme.conf"

    info "Configuring Fastfetch..."

    run "mkdir -p '$HOME/.config/fastfetch'"

    link_config \
        "$HOME/.dotfiles/fastfetch/config.jsonc" \
        "$HOME/.config/fastfetch/config.jsonc"
}
